name: TypeShell Linux

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Setup Go

          uses: actions/setup-go@v5
          with:
            go-version: '1.22.x'

        - name: Install dependencies
          run: |
            go get .
        
        - name: Build
          run: |
            go build tsh.go
        
        - name: Test
          shell: bash
          run: |
            go test ./tests -v -cover -coverprofile=coverage.out -coverpkg ./lexer,./parser,./transpiler || exit -1
            go tool cover -html=coverage.out -o coverage.html
            go tool cover -func=coverage.out

        - name: Archive code coverage
          uses: actions/upload-artifact@v4
          with:
            name: coverage.html
            path: coverage.html
