name: TypeShell Linux

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Setup Go

          uses: actions/setup-go@v5
          with:
            go-version: '1.21.x'

        - name: Install dependencies
          run: |
            go get .
        
        - name: Build
          run: |
            go build main.go
        
        - name: Test
          run: |
            go test ./tests -v
